tests/integration/actor_source_base/src/__main__.py, tests/integration/test_request_queue.py
Every now and then, the integration test for request queue times out. This adds more logging to the test so that we can debug it easier.
=> Add more logging to flaky request queue integration test

CHANGELOG.md, src/apify/event_manager.py
The `MIGRATING` platform event sends no `data` property in the message, so its parsing would fail. This fixes it.
I realized we have no unit tests for the event manager which would cover this, I will write them later.
=> Fixed parsing messages from the platform events websocket when they have no event data

.github/workflows/lint_and_type_checks.yaml, .github/workflows/release.yml, .github/workflows/run_checks.yaml, .github/workflows/unit_tests.yaml, CHANGELOG.md, tests/unit/memory_storage/resource_clients/test_dataset.py, tests/unit/memory_storage/resource_clients/test_key_value_store.py, tests/unit/memory_storage/resource_clients/test_request_queue.py
Since we test a lot of the local behavior of the SDK in unit tests, we should run those tests on Windows as well.
This PR adds Windows in the matrix by which we run the unit tests, and refactors the workflows a bit to accommodate that.
It also fixes some unit tests which were failing on Windows because the `datetime.now()` resolution is lower there, and if you ran two `datetime.now()` calls in quick succession, they would return the same value, which caused some of the timestamp checking tests in memory storage to fail.
=> Run unit tests on Windows as well

setup.py, src/apify/_utils.py, src/apify/actor.py, src/apify/event_manager.py, src/apify/log.py, src/apify/proxy_configuration.py, src/apify/storages/request_queue.py, tests/integration/actor_source_base/src/__main__.py, tests/integration/test_actor_log.py, tests/unit/actor/test_actor_helpers.py, tests/unit/actor/test_actor_log.py, tests/unit/test_proxy_configuration.py
This PR adds a new submodule, `apify.log`, and in it a `logger`, which is just a standard logger from the `logging` library, with name `apify` as per best practices for Python logging. It also makes it available under the `Actor.log` property, for convenience.
The main magic happens in the `ActorLogFormatter`, which is a log formatter that consumes the logging messages, and formats them so they are pretty:
The log formatter and handler is attached in the actor setup, so in the `__main__.py` file. We'll have to put the setup in all the Python actor templates so that it's applied in the actors by default.
The integration tests and unit tests might be too strict, and any slight change might break them, so if it happens too often, we can rewrite them a bit.
=> Add logger

CHANGELOG.md, tests/unit/test_config.py, tests/unit/test_consts.py
The `Configuration` class and the environment variables handling was not unit tested, but they're quite important, so it's better to be safe than sorry.
=> Added unit tests for `Configuration` and env vars handling

docs/docs.md, mypy.ini, setup.py, src/apify/actor.py, src/apify/proxy_configuration.py, tests/unit/test_proxy_configuration.py
This PR removes `pydantic` and replaces it with custom argument validation.
It had many drawbacks and it was not super useful for us:
- it broke marking methods as `async` in documentation
- it had ~2.5 MB (30% of all dependencies of the SDK)
- it was a pain to use correctly because it had bugs with validating nested annotated types
- we were only really using it to validate URLs
Now, the only huge dependency is the `cryptography` library, which has 5 MB, but that is much more valuable for us.
=> Remove `pydantic`

CHANGELOG.md, Makefile, setup.py, src/apify/memory_storage/resource_clients/request_queue.py, tests/unit/memory_storage/resource_clients/test_request_queue.py
This makes sure that the `RequestQueueClient` in `MemoryStorage` respects forefront, and maintains proper order of inserted requests.
This wasn't so hard in the end, I found [this neat library](https://grantjenks.com/docs/sortedcollections/valuesorteddict.html)
that takes care of keeping the requests sorted in memory.
I've also changed `orderNo` to be a `Decimal`, in milliseconds, and I've added logic that makes sure it's unique, to make the sorting work correctly.
Resolves #66.
=> Make sure local `RequestQueueClient` respects `forefront`

.github/workflows/release.yaml, CHANGELOG.md
Since we're about to release 1.0.0, we should start including it in our base images.
This will start calling the `repository_dispatch` event in https://github.com/apify/apify-actor-docker/blob/master/.github/workflows/release-python.yml#L13-L14 (and other Python image workflows), and that will start building the images.
There's also an [accompanying PR](https://github.com/apify/apify-actor-docker/pull/93) in `apify-actor-docker`, which has to be merged first.
I've also simplified the workflow a bit and rewrote it to not use third-party actions, so that we're not that vulnerable to supply chain attacks, especially since we're passing PATs with high permissions to the actions.
=> Start triggering Docker image builds on release

CHANGELOG.md, src/apify/_memory_storage/resource_clients/request_queue.py, src/apify/storages/request_queue.py, tests/unit/actor/test_actor_memory_storage_e2e.py
This fixes three bugs in `RequestQueue`:
- when loading a queue from disk, `orderNo`s were not correctly converted back to `Decimal`s
- when adding requests to the queue, even handled requests were added to the queue head
- when opening an already populated queue, if you first added another request to it before you called `fetch_next_request()`, the queue head would not contain the requests that were in the queue before you opened it
It also adds an E2E test which catches all three of these things.
=> Fixes to `RequestQueue`

.github/workflows/integration_tests.yaml
I removed `APIFY_TEST_USER_API_TOKEN` from repository secrets and keep only one from organisation.
=> feat: use test user token from organisation secrets

CHANGELOG.md, src/apify/_memory_storage/file_storage_utils.py, src/apify/_memory_storage/resource_clients/key_value_store.py, tests/unit/memory_storage/resource_clients/test_key_value_store.py
There was a bug that files in local key-value store were saved with the wrong extension, e.g. `Actor.set_value('image.png', data)` would save the record as `image.png.bin`.
This fixes it by making the filename generation more sensible:
- the `.bin` extension won't be added anymore if the content type is `application/octet-stream`.
- the record metadata is no longer saved as `{record_key}.__metadata__.json`, but as `{record_filename}.__metadata__.json`
- this makes it a lot easier to find the right metadata for a given file when opening the store
- the metadata no longer contains the `extension` attribute, just the key
- the internal record representation now contains the `filename` attribute pointing to the filename under which the record is saved.
I think the logic is a bit more readable …
=> Save local key-value store records with the correct extension

.flake8, .isort.cfg, CHANGELOG.md, pyproject.toml, src/apify/consts.py, tests/integration/test_actor_api_helpers.py
=> Bump version to 1.1.2

pyproject.toml, src/apify/_memory_storage/memory_storage_client.py, src/apify/_memory_storage/resource_clients/base_resource_client.py, src/apify/_memory_storage/resource_clients/key_value_store.py, src/apify/_utils.py, src/apify/actor.py, src/apify/event_manager.py, src/apify/storages/base_storage.py, tests/unit/actor/test_actor_lifecycle.py, tests/unit/actor/test_actor_log.py, tests/unit/memory_storage/resource_clients/test_dataset.py, tests/unit/memory_storage/resource_clients/test_request_queue.py, tests/unit/test_utils.py
I used https://pypi.org/project/flake8_simplify/ to get some insights and improved the code a bit
=> chore: Code quality improvements

pyproject.toml
We pin Apify deps versions to prevent newer packages breaking older SDK versions
=> chore: Pin apify deps versions

CHANGELOG.md, docs/docs.md, pyproject.toml, src/apify/actor.py, tests/integration/conftest.py, tests/integration/test_actor_api_helpers.py
- Closes #101 
- `Actor.reboot` method uses the new reboot endpoint which was integrated into `apify_client` in https://github.com/apify/apify-client-python/issues/137 .
- Reboot functionality cannot be tested locally, so it will have to be tested on the platform. I'll create some testing Actor and use the beta release of SDK once this PR is merged.
=> Actor.reboot method uses the new reboot endpoint

CHANGELOG.md, pyproject.toml, tests/integration/test_actor_log.py
We're changing the logging during Actor startup to also include the build ID, and this change would break the log test. This adjusts the test so that it won't fail when the platform change is released.
=> Update log integration tests after logging change on platform

CHANGELOG.md, pyproject.toml, tests/integration/test_actor_log.py
This removes the `pytest-randomly` Pytest plugin, as it doesn't play nice with `pytest-xdist`.
`pytest-randomly` (among other things) sets the random seed in the beginning of the tests to the current datetime. `pytest-xdist` runs the tests in parallel in multiple runners. When you use these two together, it happens that all of the runners have the same random seed, so if you e.g. [generate random resource names](https://github.com/apify/apify-client-python/blob/13c029e82731138cf67912fe6b375ab61846d4c5/tests/integration/test_request_queue.py#L7-L12), all runners will generate the same ones, leading to conflicts.
The other feature of `pytest-randomly`, running the tests in random order to ensure that the tests are not passing just because of some side effects caused by running in a specific …
=> Stop using `pytest-randomly` in tests

CHANGELOG.md, src/apify/storages/request_queue.py
When calling `_ensure_head_is_non_empty` on `RequestQueue`, the call to query the RQ head is cached (as an optimization) so that multiple parallel calls to the storage are not made, and in each call of `_ensure_head_is_non_empty` the cached call is then awaited.
In Python (unlike JavaScript), you can't await the result of an async function multiple times, it leads to an error. To get around that, you can wrap the result of the coroutine into an `asyncio.Task`, and that you can await multiple times (`asyncio.Task` behaves sort of like a JS `Promise` in this regard).
=> Fix issue with querying request queue head multiple times in parallel

CHANGELOG.md, src/apify/event_manager.py, src/apify/log.py
Since Actors can contain many different loggers it could be valuable to have a logger name in the log (at the beginning).
```
$ apify run --purge 
Info: All default local stores were purged.
Run: /home/vdusek/Apify/actor-templates/templates/python-scrapy/.venv/bin/python3 -m src
INFO  Initializing actor...
INFO  System info ({"apify_sdk_version": "1.1.4", "apify_client_version": "1.4.1", "python_version": "3.11.5", "os": "linux"})
INFO  Actor is being executed...
INFO  Scrapy 2.11.0 started (bot: titlebot)
INFO  Versions: lxml 4.9.3.0, libxml2 2.10.3, cssselect 1.2.0, parsel 1.8.1, w3lib 2.1.2, Twisted 22.10.0, Python 3.11.5 (main, Aug 28 2023, 00:00:00) [GCC 13.2.1 20230728 (Red Hat 13.2.1-1)], pyOpenSSL 23.2.0 (OpenSSL 3.1.2 1 Aug 2023), cryptography 41.0.3, Platform …
```
=> Update Apify log formatter to contain logger name

.github/workflows/check_version_availability.yaml, .github/workflows/run_checks.yaml, Makefile, pyproject.toml, scripts/check_version_availability.py, scripts/update_version_for_prerelease.py, scripts/utils.py
We have a recurring issue that you often forget to bump the package version number in a PR, and then when you merge it to `master`, the package publication fails because the version you're trying to publish already exists.
This adds a check to CI which detects these issues early and fails the CI, so you can't merge those PRs without bumping the package version number.
It gets skipped if the title of the PR is `docs: ...`, because such PRs don't trigger package publication when merged.
=> chore: Check whether version in PR is already released

CHANGELOG.md, pyproject.toml
Currently, we use the [inclusive ordered comparison clause](https://peps.python.org/pep-0440/#version-specifiers) in our dependency requirements (except the apify packages). 
I suggest playing safely by using a more strict [compatible release clause](https://peps.python.org/pep-0440/#version-specifiers) as we use it for the dev dependencies or dependencies in the Apify Client.
I install the dependencies using `make install-dev`, then use `pip freeze` and copy the package versions it installed - the current versions we use.
=> Add comment why not to use `~=` clause in deps definition

CHANGELOG.md, src/apify/_memory_storage/resource_clients/base_resource_client.py, src/apify/_memory_storage/resource_clients/dataset.py, src/apify/_memory_storage/resource_clients/key_value_store.py, src/apify/_memory_storage/resource_clients/request_queue.py
Using `typing_extensions.Self` does not work with the annotated `cls`, so I had to remove those. However, it's still much less `type ignores` / `noqas` in the end.
Closes #152
=> Fix type hint problems for resource clients

.github/workflows/check_version_availability.yaml, .github/workflows/integration_tests.yaml, .github/workflows/lint_and_type_checks.yaml, .github/workflows/run_checks.yaml, .github/workflows/unit_tests.yaml, CHANGELOG.md
With our [first community PR](https://github.com/apify/apify-sdk-python/pull/161) (🎉 ), there was an issue that the integration tests for the PR did not run since they could not access the API token for the test user from the repo secrets.
This changes the check workflows so that the tests run on the `pull_request_target` event, not on the `pull_request` event, which allows passing the secrets to the workflow even in case of forks. To prevent leaking the secrets, running the workflows on a PR from a fork requires approving the workflow run by a maintainer via an environment protection rule. I've put @vdusek, @janbuchar, @jirimoravcik and me as maintainers of that environment, so that we get notified in case of a fork PR and can approve the workflow runs.
The `pull_request_target` event …
=> Add option to run integration tests from PRs from forks

CHANGELOG.md, src/apify/scrapy/scheduler.py
- Do not close `nested_event_loop` in the `Scheduler.__del__`.
- Related to the https://github.com/apify/actor-templates/issues/202.
=> Do not close `nested_event_loop` in the `Scheduler.__del__`

CHANGELOG.md, src/apify/scrapy/utils.py, tests/unit/scrapy/utils/test_apply_apify_settings.py
- Related to the https://github.com/apify/apify-sdk-python/issues/176, but not solving it as a whole.
- This PR moves just a single function from a template to SDK - `apply_apify_settings`.
- The rest of the suggested changes are related to the logging. I was not able to make them work at first try. So for now let's solve it just for the settings-related helper function, and the rest will be done later.
- The changes were tested both locally and on the platform. 
- Unit tests are ready as well.
=> Add `apply_apify_settings` to Scrapy subpackage

CHANGELOG.md, pyproject.toml, src/apify/scrapy/__init__.py, src/apify/scrapy/middlewares/apify_retry.py, src/apify/scrapy/requests.py, src/apify/scrapy/scheduler.py, src/apify/scrapy/utils.py, tests/unit/scrapy/requests/test_to_apify_request.py, tests/unit/scrapy/requests/test_to_scrapy_request.py
- Based on the bug report by @JJetmar on Slack:
> There is a question regarding the RequestQueue and Python SDK:
> [Link to Slack Conversation](https://apifier.slack.com/archives/C0L33UM7Z/p1706005629066419)
>
> I tried what I could but I couldn't save any custom attributes to Request in RequestQueue with via python SDK:
>
> ```python
> await rq.add_request(request={'url': url, 'method': 'GET', 'userData': { 'myTest': 'test' } })
> ```
>
> What I get is:
>
> ```json
> {
>   "id": "7R37ec5G62ZfQHW",
>   "json": "{\n  \"url\": \"https://www.apify.com/\",\n  \"method\": \"GET\",\n  \"id\": \"7R37ec5G62ZfQHW\",\n  \"uniqueKey\": \"https://www.apify.com/\",\n  \"userData\": {\n    \"scrapy_request\": \"gASVMgIAAAAAAAB9lCiMA3VybJSMFWh0dHBzOi8vd3d3LmFwaWZ5LmNvbZSMCGNhbGxiYWNrlE6M\\nB2VycmJhY2uUTo …
```
=> Fixes conversion of `userData` and `headers` fields in Apify-Scrapy request translation

docs/01-overview/01-introduction.mdx
Hello team!
using `input` as a var name in Python is discouraged because of the built-in function by the same name. I noticed in other parts of the docs you used `actor_input` so I propose to change it here as well.
Hope this helps!
=> Change 'input' as var name

CHANGELOG.md, src/apify/scrapy/requests.py, tests/unit/scrapy/requests/test_to_apify_request.py, tests/unit/scrapy/requests/test_to_scrapy_request.py
Scrapy uses its own data structure for headers (`scrapy.http.Headers`). We need to convert it to the dictionary in `to_apify_request` to be able to serialize it. Then in the `to_scrapy_request` we need to convert it back to the `scrapy.http.Headers`.
- Closes: https://github.com/apify/actor-templates/issues/270
=> Fix conversion of `headers` fields in Apify <--> Scrapy request translation

CHANGELOG.md, src/apify/scrapy/requests.py, src/apify/scrapy/scheduler.py, tests/unit/scrapy/requests/test_to_apify_request.py
The PR addresses the problem identified in [Issue #189](https://github.com/apify/apify-sdk-python/issues/189), where `to_apify_request` could fail silently during serialization of the Scrapy request. This PR has introduced enhanced error handling to ensure users are informed if serialization of a request fails, preventing the request from being not enqueued without notification.
=> Improve error handling for `to_apify_request` serialization failures

docs/03-concepts/01-actor-lifecycle.mdx, docs/03-concepts/04-actor-events.mdx, docs/03-concepts/11-configuration.mdx
After we've split off `apify_shared`, we forgot to update the consts imports in the docs. This fixes it.
Also fixes one typo with `Actor.off()`.
=> docs: Small docs fixes

CHANGELOG.md, pyproject.toml, src/apify/_utils.py, src/apify/scrapy/requests.py, src/apify/scrapy/scheduler.py, src/apify/storages/request_queue.py, tests/unit/test_utils.py
- Updates `RequestQueue.add_request` method by improving its unique key generation logic.
- The logic is exposed via new optional parameters of `add_request`.
- I also extended the docstring to make clear what it does (mainly regarding the deduplication).
- The PR introduces 3 new "helper" functions in the `apify/_utils.py`:
- `get_short_base64_hash` based on the [_hashPayload](https://github.com/apify/crawlee/blob/v3.8.1/packages/core/src/request.ts#L397:L405).
- `normalize_url` based on the [normalizeUrl](https://github.com/apify/apify-shared-js/blob/%40apify/input_schema%403.5.15/packages/utilities/src/utilities.client.ts#L128:L158).
- `compute_unique_key` based on the [_computeUniqueKey](https://github.com/apify/crawlee/blob/v3.8.1/packages/core/src/request.ts#L381-L395).
- Use this …
=> Improve unique key generation logic

CHANGELOG.md, src/apify/actor.py
- closes #200
I could not find the actual reason why the linked run got stuck, but this should make the Actor cleanup more robust as a whole.
=> fix: Set a timeout for Actor cleanup

CHANGELOG.md, pyproject.toml, src/apify/config.py
This PR adds Actor Standby port to the configuration.
=> feat: add actor standby port

.github/workflows/check_version_availability.yaml, .github/workflows/docs.yaml, .github/workflows/integration_tests.yaml, .github/workflows/lint_and_type_checks.yaml, .github/workflows/unit_tests.yaml
This is so that CI can pass for #210... eventually. Crawlee does not support 3.8.
=> ci: Stop testing python 3.8

docs/03-concepts/01-actor-lifecycle.mdx, docs/03-concepts/04-actor-events.mdx, docs/03-concepts/11-configuration.mdx
- **Remove mention of Actor.main**
- **Update example**
- **Update example**
=> docs: Update a part of docs for 2.0

src/apify/scrapy/middlewares/apify_proxy.py, tests/unit/scrapy/middlewares/test_apify_proxy.py
From the template log... it scrapes normally as it should...
```
...
2024-09-02T21:34:06.9322150Z [title_spider] [INFO] TitleSpider is parsing <200 https://apify.com/run-scrapy-in-cloud>... ({"spider": "<TitleSpider 'title_spider' at 0x7f70c7ab07f0>"})
2024-09-02T21:34:06.9455173Z [title_spider] [INFO] TitleSpider is parsing <200 https://docs.apify.com/academy/web-scraping-for-beginners>... ({"spider": "<TitleSpider 'title_spider' at 0x7f70c7ab07f0>"})
2024-09-02T21:34:06.9530763Z [title_spider] [INFO] TitleSpider is parsing <200 https://apify.com/success-stories>... ({"spider": "<TitleSpider 'title_spider' at 0x7f70c7ab07f0>"})
2024-09-02T21:34:07.0125374Z [title_spider] [INFO] TitleSpider is parsing <200 https://apify.com/templates/ts-crawlee-playwright-chrome>... ({"spider": …
```
=> fix: possible infinity loop in Apify-Scrapy proxy middleware

Makefile, website/build_api_reference.sh
Ever since #247, the reference docs build started failing (rendering only a blank page). This is probably caused by the new `poetry` migration (and lack of `poetry run` in the right places).
=> docs: fix `/reference` docs build

src/apify/_crypto.py, src/apify/_platform_event_manager.py, src/apify/_proxy_configuration.py, src/apify/log.py, src/apify/scrapy/requests.py, src/apify/scrapy/utils.py, website/pydoc-markdown.yml, website/transformDocs.js
Slightly bends the `transformDocs.js` script to accommodate the new structure of the project better. 
https://github.com/user-attachments/assets/3cbd0835-165c-4fae-95b0-c1d45bed8061
At the offsite, we talked about the need for a better solution than this. With three publically documented Python projects, the current solution is becoming insufficient. 
The next Python docs steps are documented in https://github.com/apify/crawlee-python/issues/324
Closes #270
=> docs: hotfix API reference docs

website/build_api_reference.sh, website/docusaurus.config.js, website/pydoc-markdown/generate_ast.py, website/pydoc-markdown/google_docstring_processor.py, website/src/css/custom.css, website/transformDocs.js
Replaces the default `pydoc-markdown` shell script with a custom Python script calling the `pydoc-markdown` API directly. A custom patch of `GoogleProcessor` allows us to parse the Google-style docstrings and render the parameter comments with the actual parameters.
=> docs: add Google-style docstring parser

tests/unit/scrapy/requests/test_to_apify_request.py
Needs https://github.com/apify/crawlee-python/pull/562
=> fix: adjust tests of scrapy user data

src/apify/_configuration.py
This does nothing on runtime, it's just housekeeping.
=> chore: Add deprecation notice to actor standby port variable

src/apify/_configuration.py
This PR introduces a new environment variable with standby URL, it also changes the default port for the standby port env var.
=> feat: add standby URL, change default standby port

.github/workflows/build_and_deploy_docs.yaml, .github/workflows/run_code_checks.yaml, .github/workflows/run_release.yaml, Makefile
- fix python version reference
- fix shared workflows reference
- update path to shared workflows
- use pull request for code checks
- fix docs build
=> ci: update workflows and fix Python version reference

src/apify/_configuration.py
- closes https://github.com/apify/crawlee-python/issues/596
=> fix: Allow empty timeout_at env variable

.github/workflows/run_release.yaml
=> chore: remove temporarily integration tests for releases

.github/workflows/run_release.yaml, src/apify/scrapy/middlewares/apify_proxy.py, src/apify/scrapy/pipelines/actor_dataset_push.py, src/apify/scrapy/scheduler.py, tests/integration/README.md, tests/integration/conftest.py, tests/integration/test_actor_api_helpers.py, tests/integration/test_actor_create_proxy_configuration.py, tests/integration/test_actor_dataset.py, tests/integration/test_actor_events.py, tests/integration/test_actor_key_value_store.py, tests/integration/test_actor_lifecycle.py, tests/integration/test_actor_log.py, tests/integration/test_actor_request_queue.py, tests/integration/test_fixtures.py, tests/integration/test_request_queue.py, tests/unit/conftest.py
Both the build Actor step and the run Actor step.
Closes #301
=> ci: Make integrations tests more stable

pyproject.toml
New version 14 introduces some backward incompatible changes that are breaking existing code.
=> fix: Set version constraint of the `websockets` dependency to <14.0.0

pyproject.toml, src/apify/apify_storage_client/_dataset_client.py, tests/integration/test_actor_dataset.py
Fix iter_items to correctly work in async iteration. Add test.
- closes #320
=> fix: Fix Dataset.iter_items for apify_storage

poetry.lock, pyproject.toml, src/apify/scrapy/requests.py, tests/unit/scrapy/pipelines/test_actor_dataset_push.py, tests/unit/scrapy/requests/test_to_apify_request.py, tests/unit/scrapy/requests/test_to_scrapy_request.py
- Add a version upper boundary for Crawlee as 0.5 will break the compatibility (mostly due to the changes in the service container).
- And fix (new) type errors.
=> chore: Add version upper boundary for Crawlee

pyproject.toml, src/apify/_configuration.py, tests/integration/test_actor_events.py, tests/unit/actor/test_actor_create_proxy_configuration.py, tests/unit/actor/test_actor_env_helpers.py, tests/unit/scrapy/middlewares/test_apify_proxy.py, tests/unit/test_proxy_configuration.py
- Rm ignore of `PGH003` rule and update type ignores to be specific.
- Rm the comment about deps in the pyprojtoml, as it is obvious now probably.
=> chore: Use specific rule codes when ignoring type issues

docs/02-guides/01-requests-and-httpx.mdx, docs/03-concepts/05-proxy-management.mdx, poetry.lock, pyproject.toml, src/apify/_proxy_configuration.py, tests/unit/conftest.py
- HTTPX 0.27 supports both the `proxies` and `proxy` args, while version 0.28 supports only the `proxy`. 
- I am adopting the updated arg name to align with the newer version. 
- However, we cannot fully upgrade to 0.28 as there are more issues.
=> fix: add upper bound of HTTPX version

tests/unit/actor/test_actor_lifecycle.py
@Pijukatel investigated this, tried to reproduce it locally, without much success. I believe we can skip it for Py 3.13, correct?
=> chore: skip python 3.13 flaky test

poetry.lock, pyproject.toml, src/apify/_configuration.py, tests/unit/actor/test_actor_env_helpers.py
We have added a few new environment variables:
- `ACTOR_BUILD_TAGS`
- `ACTOR_FULL_NAME`
- `ACTOR_MAX_TOTAL_CHARGE_USD`
This adds corresponding config variables to `Actor.config`. `ACTOR_BUILD_TAGS` is a comma-separated list of build tags, so I've added a mechanism to parse the string environment variable into a list.
=> feat: add new config variables to `Actor.config`

docs/01_overview/01_introduction.mdx, docs/01_overview/02_running_actors_locally.mdx, docs/01_overview/03_actor_structure.mdx, docs/02_guides/01_beautifulsoup_httpx.mdx, docs/02_guides/02_crawlee.mdx, docs/02_guides/03_playwright.mdx, docs/02_guides/04_selenium.mdx, docs/02_guides/05_scrapy.mdx, docs/03_concepts/01_actor_lifecycle.mdx, docs/03_concepts/02_actor_input.mdx, docs/03_concepts/03_storages.mdx, docs/03_concepts/04_actor_events.mdx, docs/03_concepts/06_interacting_with_other_actors.mdx, docs/03_concepts/07_webhooks.mdx, docs/03_concepts/08_access_apify_api.mdx, docs/03_concepts/09_running_webserver.mdx, docs/03_concepts/10_logging.mdx, docs/03_concepts/11_configuration.mdx
I broke some links in #378, so this update fixes them. Additionally, there are some cosmetic changes, such as updating the titles to the correct case format.
=> docs: fix links and some headings

src/apify/_actor.py, src/apify/scrapy/middlewares/apify_proxy.py, src/apify/scrapy/scheduler.py
Relates: https://github.com/apify/actor-templates/issues/303
=> fix: Fix RQ usage in Scrapy scheduler

src/apify/_actor.py, tests/unit/actor/test_actor_lifecycle.py, tests/unit/actor/test_actor_non_default_instance.py, tests/unit/conftest.py
=> fix: Make sure that Actor instances with non-default configurations are also accessible through the global Actor proxy after initialization

website/package-lock.json, website/package.json
Introduces recent features and fixes from the plugin.
Enables docs versioning for Python projects.
Handles `TypeAlias`ed types (expands known aliases to their values).
Fixes an issue with `Unpack` type in reexported types - below screenshot of Crawlee's Dataset in Apify SDK Python docs (see that the `Unpack`-type kwargs are not expanded) :
=> docs: bump `typedoc-api` plugin

docs/03_concepts/03_storages.mdx
Add small docs section about how to use `force_cloud` argument in local development.
Documents #412
=> docs: Add force_cloud argument documentation

src/apify/_actor.py, tests/unit/actor/test_actor_log.py
- Introduced a new `exit_process` option for the Actor class.
- Named the option `exit_process` (instead of `exit`) to avoid shadowing Python's built-in names.
- Set reasonable defaults: `False` for IPython, Pytest, and Scrapy environments, and `True` for all other cases.
- Updated the `test_actor_logs_messages_correctly` test accordingly.
- Closes: #396
- Closes: #401
- Tests are passing, including the Scrapy integration test.
=> feat: add Actor `exit_process` option

pyproject.toml, src/apify/_actor.py, src/apify/scrapy/requests.py, tests/unit/actor/test_actor_lifecycle.py, uv.lock
There is a new rule [TC006](https://docs.astral.sh/ruff/rules/runtime-cast-value/).
=> chore: update Ruff to v0.10

pyproject.toml, uv.lock
I removed the `build` in https://github.com/apify/apify-sdk-python/pull/433, , but it's being used for the integration tests -  [tests/integration/conftest.py#L132](https://github.com/apify/apify-sdk-python/blob/30bdcf2dc247313d2b1bd7122d37a1338ec43e49/tests/integration/conftest.py#L132), so I'm reverting it.
=> chore(deps): add build dev dep

pyproject.toml, src/apify/_actor.py, src/apify/_utils.py, src/apify/scrapy/_async_thread.py, src/apify/storages/_request_list.py, uv.lock
- Currently, our docstrings use a mix of imperative and indicative moods basically randomly.
- PEP 257 recommends using the imperative mood for the first line of docstrings, which is also enforced by the Ruff rule [D401](https://docs.astral.sh/ruff/rules/non-imperative-mood/#non-imperative-mood-d401). So I believe the imperative form is more suitable for the docs purposes.
- In most cases, I have simply changed the verb form, but a few cases required more rewording.
- I updated the pyproject configuration to enforce it.
=> docs: Use and enforce imperative mood

website/package-lock.json, website/package.json
Introduces fixes from https://github.com/apify/apify-docs/pull/1427 into the documentation of this project.
=> docs: fix changelog generation by bumping `@apify/docs-theme` plugin

src/apify/_platform_event_manager.py
Apify reports CPU utilization as the sum of utilization of all CPUs, but Crawlee expects a number between 0 and 1. Because of this, it is impossible for AutoscaledPool to scale beyond one CPU.
=> fix: Fix calculation of CPU utilization from SystemInfo events

src/apify/_proxy_configuration.py, tests/unit/test_proxy_configuration.py
Fetch proxy password from /user/me using `ApifyEnvVars.TOKEN` only when not passed through the constructor or `ApifyEnvVars.PROXY_PASSWORD` is not provided.
=> fix: prefer proxy password from env var 

pyproject.toml, uv.lock
This will be backported to https://github.com/apify/apify-sdk-python/tree/release-v2 branch and a new patch will be released.
=> fix: Restrict apify-shared and apify-client versions

pyproject.toml, tests/unit/actor/test_actor_create_proxy_configuration.py, tests/unit/actor/test_request_list.py, tests/unit/conftest.py, tests/unit/test_proxy_configuration.py, uv.lock
- Replace `respx` mocks with `pytest-httpserver` in tests
=> chore: Replace `respx` mocks with `pytest-httpserver` in tests

src/apify/storage_clients/_apify/_models.py, src/apify/storage_clients/_apify/_request_queue_client.py, tests/integration/test_actor_request_queue.py, tests/integration/test_crawlers_with_storages.py
=> fix: Try to solve race conditions

src/apify/_actor.py, src/apify/events/_apify_event_manager.py
- Resolve DeprecationWarning in ApifyEventManager.
- Polish docstrings.
- Closes: #343
=> fix: Resolve DeprecationWarning in ApifyEventManager

pyproject.toml, tests/integration/actor_source_base/requirements.txt, uv.lock
Update to Crawlee v1.0.0rc1 to be able to release SDK v3.0.0rc1.
=> chore: Update to Crawlee v1.0.0rc1

docs/04_upgrading/upgrading_to_v3.md, src/apify/_configuration.py, src/apify/storage_clients/_apify/_dataset_client.py, src/apify/storage_clients/_apify/_key_value_store_client.py, src/apify/storage_clients/_apify/_request_queue_client.py, src/apify/storage_clients/_apify/_utils.py, tests/integration/test_apify_storages.py
- Using unnamed Apify-based storage locally outside of the Apify platform will use the alias mechanism.
Closes: #599 
Added unit tests
=> refactor!: Make default Apify storages use alias mechanism
